### ISSUE TITLE
Readme Dependencies should only link to Blocks install

### ISSUE THREAD

**Issue by udibr** [jbornschein/draw#1]
Blocks installation http://blocks.readthedocs.org/en/latest/setup.html
includes an install of Theano, Fuel and picklable-itertools which are also needed
(see https://github.com/bartvm/blocks/blob/master/requirements.txt )
so there is no need to list them again

On the other hand you need to prepare the data and set fuel path
http://blocks.readthedocs.org/en/latest/tutorial.html#training-your-model

you also need
pip install ipdb

you also need to download binarized mnist
https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/datasets/download_binarized_mnist.py

**Comment by jbornschein** [comment]
Thanks for the enhancements!
