### ISSUE TITLE
Unable to satisfy dependencies

### ISSUE THREAD

**Issue by dsc-dsc-dsc** [jbornschein/draw#11]
I'm running debian stretch, I have installed seemingly everything necessary, yet the program still has an error, particularly at line 32:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/dash/draw/draw/train-draw.py in <module>()
     30 from blocks.monitoring import aggregation
     31 from blocks.extensions import FinishAfter, Timing, Printing, ProgressBar
---> 32 from blocks.extensions.plot import Plot
     33 from blocks.extensions.saveload import Checkpoint, Dump
     34 from blocks.extensions.monitoring import DataStreamMonitoring, TrainingDataMonitoring

ImportError: No module named plot
```

If you could cover this better in the readme, it would greatly help, thanks!

**Comment by jbornschein** [comment]
Blocks is kind of a fast evolving project -- quite some things changed in the last month(s)

E.g: The Plot extension is now in the blocks-extra package -- you need to install it and import
  from blocks.extras.extensions.plot import Plot

But I expect there are many more similar small changes.

I'll try up update this code to the last version of Blocks and Fuel ASAP

**Comment by jbornschein** [comment]
I think it should work again with the latest versions of blocks and fuel -- but I didn't test it thoroughly. So please let me know if it works and feel free to open this issue again if there's still a compatibility problem.

**Comment by kadir-gunel** [comment]
Shouldn't be  **from blocks_extras.extensions.plot import Plot** ?
