### ISSUE TITLE
Maximum recursion depth in Checkpoint.

### ISSUE THREAD

**Issue by jbornschein** [jbornschein/draw#16]
With recent versions of blocks we reliably get `RuntimeError: maximum recursion depth exceeded` .. even when setting a very high maximum recursion limit.

**Comment by jbornschein** [comment]
@dribnet reports in #10 that the issue can be solved by setting a high maximum recursion limit.

**Comment by dribnet** [comment]
I was mistaken about high recursion limit fixing this - it was something else I had done in testing that gets checkpointing to work: setting `--niter=1`. Obviously not a general solution. But interesting to note that this is something about the network itself that is causing this - probably circular or self-references. I should be able to try a couple of things over the weekend - though it might require a custom Checkpointer or blocks change I think.
