### ISSUE TITLE
draw not compatible with latest blocks

### ISSUE THREAD

**Issue by dribnet** [jbornschein/draw#22]
The current draw code is again incompatible with the latest version of blocks (currently [49a12a3](https://github.com/mila-udem/blocks/commit/49a12a37)). This seems to mainly be due to the API change in mila-udem/blocks#725 and I have a fix for this in my [blocks_fix](https://github.com/dribnet/draw/tree/blocks_fix) branch. Unfortunately, this change also invalidates all previous pickled models, so I'm going to hold off on a merge request until I can train a new models for the README update.

**Comment by tigerneil** [comment]
@dribnet thanks so much. it works now.

**Comment by jbornschein** [comment]
#28 (@dibnets fix; thanks!) and #29 should fix it for now.
