### ISSUE TITLE
ImportError: cannot import name AbstractMode

### ISSUE THREAD

**Issue by faizan94** [jbornschein/draw#25]
ImportError                               Traceback (most recent call last)
/home/muslimboy/Desktop/data/draw/train-draw.py in <module>()
     48 import draw.datasets as datasets
     49 from draw.draw import *
---> 50 from draw.samplecheckpoint import SampleCheckpoint
     51 from draw.partsonlycheckpoint import PartsOnlyCheckpoint
     52 

/home/muslimboy/Desktop/data/draw/draw/samplecheckpoint.py in <module>()
      8 from blocks.extensions.saveload import Checkpoint
      9 
---> 10 from sample import generate_samples
     11 
     12 

/home/muslimboy/Desktop/data/draw/sample.py in <module>()
     13 from PIL import Image
     14 from blocks.main_loop import MainLoop
---> 15 from blocks.model import AbstractModel
     16 from blocks.config import config
     17 

ImportError: cannot import name AbstractModel

**Comment by aferriss** [comment]
I'm getting the same thing fwiw

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/adamferriss/Desktop/draw/train-draw.py in <module>()
     48 import draw.datasets as datasets
     49 from draw.draw import *
---> 50 from draw.samplecheckpoint import SampleCheckpoint
     51 from draw.partsonlycheckpoint import PartsOnlyCheckpoint
     52 

/Users/adamferriss/Desktop/draw/draw/samplecheckpoint.py in <module>()
      8 from blocks.extensions.saveload import Checkpoint
      9 
---> 10 from sample import generate_samples
     11 
     12 

/Users/adamferriss/Desktop/draw/sample.py in <module>()
     13 from PIL import Image
     14 from blocks.main_loop import MainLoop
---> 15 from blocks.model import AbstractModel
     16 from blocks.config import config
     17 

ImportError: cannot import name AbstractModel
```

**Comment by faizan94** [comment]
I got it solved when I reinstall everything. I think the problem was that I had older version of blocks.
