### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'parameters'

### ISSUE THREAD

**Issue by faizan94** [jbornschein/draw#26]
TypeError                                 Traceback (most recent call last)
/home/muslimboy/Desktop/drawpython/draw/train-draw.py in <module>()
    287     args = parser.parse_args()
    288 
--> 289     main(**vars(args))

/home/muslimboy/Desktop/drawpython/draw/train-draw.py in main(name, dataset, epochs, batch_size, learning_rate, attention, n_iter, enc_dim, dec_dim, z_dim, oldmodel, live_plotting)
    179         step_rule=CompositeRule([
    180             StepClipping(10.),
--> 181             Adam(learning_rate),
    182         ])
    183         #step_rule=RMSProp(learning_rate),

/home/muslimboy/anaconda/lib/python2.7/site-packages/blocks/algorithms/**init**.pyc in **init**(self, step_rule, gradients, known_grads, **kwargs)
    191         if gradients:
    192             kwargs.setdefault("params", gradients.keys())
--> 193         super(GradientDescent, self).**init**(**kwargs)
    194 
    195         self.gradients = gradients

**Comment by jbornschein** [comment]
Looks like you are using a older/inconsistent version of Blocks.

That parameter was changed from "param" to "parameters" in 

https://github.com/mila-udem/blocks/commit/ca0a000ef831d7791abb00852b24151128ad4516

see 

https://github.com/mila-udem/blocks/blob/master/blocks/algorithms/__init__.py#L212

**Comment by muslimboy1994** [comment]
Now I am having other issue.

ImportError                               Traceback (most recent call last)
/home/muslimboy/Desktop/drawpython/draw/train-draw.py in <module>()
     47 
     48 import draw.datasets as datasets
---> 49 from draw.draw import *
     50 from draw.samplecheckpoint import SampleCheckpoint
     51 from draw.partsonlycheckpoint import PartsOnlyCheckpoint

/home/muslimboy/Desktop/drawpython/draw/draw/draw.py in <module>()
     13 from blocks.bricks.recurrent import BaseRecurrent, recurrent
     14 from blocks.bricks import Random, Initializable, MLP, Linear
---> 15 from blocks.bricks import Identity, Tanh, Logistic
     16 
     17 from attention import ZoomableAttentionWindow

ImportError: cannot import name Logistic

**Comment by faizan94** [comment]
Thanx for the help.
